name: dex_app
description: "PokeHub - A Flutter application to explore Pokemon data."
publish_to: 'none'
version: 1.1.2+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  sqflite: ^2.3.0
  cached_network_image: ^3.2.3
  animations: ^2.0.6
  flutter_staggered_grid_view: ^0.6.2 
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.14.4
  in_app_update: ^4.2.3
  package_info_plus: ^8.3.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.3.2
  open_file: ^3.5.10
  flutter_gen: ^5.12.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/database/
    - assets/imagenes/placeholder.png
    - assets/imagenes/pokemon/Kanto/
    - assets/imagenes/pokemon/Johto/
    - assets/imagenes/pokemon/Hoenn/
    - assets/imagenes/pokemon/Sinnoh/
    - assets/imagenes/pokemon/Unova/
    - assets/imagenes/pokemon/Kalos/
    - assets/imagenes/pokemon/Alola/
    - assets/imagenes/pokemon/Galar/
    - assets/imagenes/pokemon/Paldea/
    - assets/imagenes/pokemon/Formas-Especiales/
